import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MarketplaceProvider } from "@/components/providers/marketplace";
import { AuthProvider } from "@/components/providers/auth";
import { AppSettingsProvider } from "@/components/providers/app-settings-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MarketplaceProvider>
          <AuthProvider>
            <AppSettingsProvider name="vercel" description="Vercel (AI Gateway)">
              {children}
            </AppSettingsProvider>
          </AuthProvider>
        </MarketplaceProvider>
      </body>
    </html>
  );
}
